---
- name: "Create directory secret"
  file:
    path: "/home/{{ new_user }}/.secrets"
    state: directory
    mode: '0700'

- name: "Create cloudflare credentials file"
  template:
    src: ../../templates/cloudflare/cloudflare_ini.j2
    dest: "/home/{{ new_user }}/.secrets/cloudflare.ini"
    mode: '0400'

- name: "Run Certbot to generate certificates"
  command: >
    certbot certonly
    --dns-cloudflare
    --dns-cloudflare-credentials /home/{{ new_user }}/.secrets/cloudflare.ini
    --agree-tos
    --non-interactive
    --email lawrencenoman@gmail.com
    --domains *.olen.studentdumbways.my.id -v
  timeout: 60